---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ./config:/config
      - /mnt/usb/Videos/Tv:/tv
      - /mnt/usb/Videos/Movies:/movies
    restart: unless-stopped
