version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - /selfhosted/jellyfin/config:/config
      - /selfhosted/jellyfin/cache:/cache
      - /mnt/usb:/media   #please change the path to your media
    restart: "unless-stopped"
