version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /YourPath:/media   #please change the path to your media
    restart: "unless-stopped"
