---
version: "2.1"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: bridge
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=14400
      - WATCHTOWER_REVIVE_STOPPED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
